import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import './index.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>
                    <ul style={{}}>
                        <li>
                            <Link href="/">Home</Link>
                        </li>
                        <li>
                            <Link href="/dice">Throw Dices</Link>
                        </li>
                        <li>
                            <Link href="/prime">Prime Generator</Link>
                        </li>
                    </ul>
                </nav>
                <div>{children}</div>
            </body>
        </html>
    );
}
